### ISSUE TITLE
Doesn't work with htmlparser2?

### ISSUE THREAD

**Issue by kyrylkov** [FontoXML/fontoxpath#282]
With the following code, we get the error below"

```
const {
  parseDocument
} = require('htmlparser2');
const {
  evaluateXPathToString
} = require('fontoxpath')
......
const doc = parseDocument(text);
const result = evaluateXPathToString(`//${PLATFORM_CORE}:webservicesDomain`, doc, undefined, {}, {namespaceResolver});
```

```
[CATCH][msg] --> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at pb.getChildNodes (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:81:1101)
    at Ab (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:84:140)
    at zb (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:84:27)
    at Qf.evaluate (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:277:332)
    at N (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:181:439)
    at Object.next (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:325:335)
    at l (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:321:256)
    at Zg (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:321:282)
    at C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:326:52
    at Array.reduce (<anonymous>)
    at dh.evaluate (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:325:67)
    at N (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:181:439)
    at ah.evaluate (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:324:438)
    at N (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:181:439)
    at Z (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:452:52)
    at ak (C:\Users\dev\server\node_modules\fontoxpath\dist\fontoxpath.js:454:1122)
```

**Comment by DrRataplan** [comment]
Hey there!

Hm, this looks like a library that did not implement the same interface for Node as FontoXPath expects: the Processing Instruction node does not implement the childNodes property, even though it is present on the base class (Node): https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes.

FontoXPath should not try to get these childNodes. It already does a check for this. This check fails though because in the htmlparser2 library you have there, Processing Instructions have a nodeType set to 1. That is Node.ELEMENT_NODE. I think this is a clear bug with the htmlparser2 library.

In summary, there are two bugs: PIs should have the nodeType property set to 7: Node.PROCESSING_INSTRUCTION_NODE and they should implement the childNodes property.

At Fonto and in several of my private projects, we have used the [slimdom](https://github.com/bwrrp/slimdom.js) DOM implementation (sometimes with the [slimdom-sax-parser](https://github.com/wvbe/slimdom-sax-parser) library for XML parsing). These libraries have a great track record and are spec-compliant. I'd recommend these also because you are going to work with namespaces and the HTML specification does not really do namespaces in any meaningful way.

I hope this helps! Please give us a note if we can help you any further!

Regards,

Martin

**Comment by DrRataplan** [comment]
For future reference, this is quite the minimal repro of the issue at hand:

```
const {
  parseDocument
} = require('htmlparser2');
const {
  evaluateXPathToString
} = require('fontoxpath');

const text = '<root>child/>prrt<!--comment--><?pi data?></root>';

const doc = parseDocument(text);
const result = evaluateXPathToString(`//root`, doc);
```

**Comment by kyrylkov** [comment]
@DrRataplan Got it.  Thanks.  We just tried xmlbuilder2 dom and it works fine.  At least this specific example.
