### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by devatwork** [FontoXML/fontoxpath#354]
Found by #349 

!!! Crash found !!!
Selector: `array:fold-left([1,2,3], [], function($x, $y){[$x, ?y]})`
Language: `XPath3.1`
```
TypeError: Cannot read property 'type' of null
    at gs (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:277:240)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:138
    at Array.reduce (<anonymous>)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:110
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:61:434
    at Xc.E.O (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:61:446)
    at hs (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:87)
    at js.evaluate (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:633)
    at ok (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:164:458)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:219:889
```

**Comment by devatwork** [comment]
!!! Crash found !!!
Selector: `fn:fold-left((true(), false(), false()), false(), function($a, $b) {
                  ?a and $b })`
Language: `XQueryUpdate3.1`
```
TypeError: Cannot read property 'type' of null
    at gs (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:277:240)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:138
    at Array.reduce (<anonymous>)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:110
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:61:434
    at Xc.E.O (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:61:446)
    at hs (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:87)
    at js.evaluate (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:633)
    at ok (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:164:458)
    at Object.next (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:248:483)
```
