### ISSUE TITLE
Cannot read property 'P' of null

### ISSUE THREAD

**Issue by devatwork** [FontoXML/fontoxpath#356]
Found by #349 

!!! Crash found !!!
Selector: `array:sort([(1,0), (1,1)? (0,B), (0,0)])`
Language: `XQuery3.1`
```
TypeError: Cannot read property 'P' of null
    at Gm.evaluate (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:219:2153)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:177:781
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:263:286
    at Array.map (<anonymous>)
    at In.v (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:263:263)
    at In.Ml.evaluate (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:177:724)
    at ok (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:164:458)
    at hs (C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:67)
    at C:\fontoxml\platform\fontoxpath\dist\fontoxpath.esm.js:278:416
    at Array.reduce (<anonymous>)
```

**Comment by DrRataplan** [comment]
Link to playground repro: https://xpath.playground.fontoxml.com/?state=H4sIALj%2FvmIAA6tWys1PSVWyMtBRKkssykxMykktVrJSqq5V0lGqyM0BMm2AlL4diBtYmlpUCRRJLCpKrLQqzi8q0YjWMNQx0NRRAFKGmvYKGgY6TiCeAVAwVhOoJzk%2FryS1ogSmU6kWAJcACk1wAAAA
