### ISSUE TITLE
Problem with copy-modify-return nested in FLWOR

### ISSUE THREAD

**Issue by rrthomas** [FontoXML/fontoxpath#446]
copy-modify-return only works on one element at a time, so I try nesting it inside a FLWOR:

```typescript
import {evaluateUpdatingExpressionSync, executePendingUpdateList, registerXQueryModule} from 'fontoxpath'
import slimdom from 'slimdom'

registerXQueryModule(`
module namespace my-custom-namespace = "my-custom-uri";
(:~ Insert attribute somewhere ~:)
declare %public %updating function my-custom-namespace:do-something($elems as element()*) as node()* {
  for $ele in $elems
  return
  copy $a := $ele
  modify replace value of node $a/@foo with "bar"
  return $a
};
`)
// At some point:
const doc = new slimdom.Document()
const top = doc.createElement('top')
const elem = doc.createElement('element')
const elem2 = doc.createElement('element')
elem.setAttribute('foo', 'foo')
elem2.setAttribute('foo', 'foo')
top.appendChild(elem)
top.appendChild(elem2)
doc.appendChild(top)
const contextNode = doc.firstChild
const pendingUpdatesAndXdmValue = evaluateUpdatingExpressionSync(
  'ns:do-something(//element)',
  contextNode,
  null,
  null,
  {moduleImports: {ns: 'my-custom-uri'}, debug: true},
)

console.log(slimdom.serializeToWellFormedString(
  pendingUpdatesAndXdmValue.xdmValue,
))

executePendingUpdateList(pendingUpdatesAndXdmValue.pendingUpdateList);
```

This gives a TypeScript error:

```
/home/rrt/Software/ruth/node_modules/slimdom/src/util/errorHelpers.ts:11
		throw new TypeError(`Value should be an instance of ${Constructor.name}`);
        ^
TypeError: Value should be an instance of Node
    at expectObject (/home/rrt/Software/ruth/node_modules/slimdom/src/util/errorHelpers.ts:11:9)
    at asObject (/home/rrt/Software/ruth/node_modules/slimdom/src/util/typeHelpers.ts:18:2)
    at Object.t.serializeToWellFormedString (/home/rrt/Software/ruth/node_modules/slimdom/src/dom-parsing/XMLSerializer.ts:49:9)
    at Object.<anonymous> (/home/rrt/Software/ruth/src/update.ts:34:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/rrt/Software/ruth/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/home/rrt/Software/ruth/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

Am I doing something wrong?

**Comment by DrRataplan** [comment]
That _might_ be because that `serializeToWelformedString` is being passed an array of nodes, instead of a single node. Could you try to either insert the nodes under a common element, or looping over those Node XDM values?

**Comment by DrRataplan** [comment]
Hey @rrthomas,

Was the problem what I expected with an unfortunate array of nodes? The `ANY` return type is nasty and I am working on deprecating that. Just need a quiet week to adapt a bunch of internal Fonto APIs before I can do so.

Regards,

Martin

**Comment by rrthomas** [comment]
Changing the logging to:

```typescript
for (const node of pendingUpdatesAndXdmValue.xdmValue) {
  console.log(slimdom.serializeToWellFormedString(node))
}
```

makes it work fine, thanks! Not sure what went wrong with my original use case; I shall see if I can work towards it from here.
